version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:14
  working_directory: ~/dora-sdk-ts

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: npm run test

workflows:
  version: 2
  build:
    jobs:
      - test
